#!/usr/bin/env bash
# lyx-theme - JankyBorders (Osaka Jade)
# Read automatically by `borders` when invoked without arguments.  man borders

exec borders \
    style=round \
    width=7.0 \
    hidpi=on \
    active_color=0xff509475 \
    inactive_color=0xff23372b \
    blacklist="Ghostty Quick Terminal"
